# Cross shell aliases
alias ls='ls --color=auto'
alias l.='ls -d .* --color=auto'
alias ll='ls -lh --color=auto'
alias lsl='ls -lh --color=auto'
alias lsa='ls -lha --color=auto'
alias g='git'
alias mk='minikube'
alias kc='kubectl'
alias ap='ansible-playbook'
