# Cross shell aliases
alias ls='ls --color=auto'
alias l.='ls -d .* --color=auto'
alias ll='ls -lh --color=auto'
alias lsl='ls -lh --color=auto'
alias lsa='ls -lha --color=auto'
alias g='git'
alias mk='minikube'
alias kc='kubectl'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias rmf='rm -f'
alias grep='rg'
alias df='df -h'
alias du='du -h'
alias bc='bc -l'
alias less='less -r'
alias rgp="rg -p"
