wtf:
  colors:
    background: black
  #   highlight:
  #     fore: black
  #     back: white
  mods:
    spotify:
      type: spotify
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 1
    jira:
      domain: "https://embedintel.atlassian.net"
      email: "bryant@embedintel.com"
      enabled: true
      jql: "assignee = currentUser() AND project = 'LWLL'"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      project: "LWLL"
      username: "bryant"
      verifyServerCertificate: true
    battery:
      type: power
      title: "⚡️"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
    security_info:
      type: security
      enabled: true
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 3600
    cmdrunner:
      enabled: true
      args: ["-c", "az vm list-usage --location eastus --out table | grep NCS"]
      cmd: /bin/bash
      refreshInterval: 300
      position:
        top: 0
        left: 2
        height: 1
        width: 1
