export DOTFILES="${HOME}/.dotfiles"
source "${DOTFILES}/sh/functions.sh"

# OS specific setups
_uname=$(uname)
case ${_uname} in
    Linux)
        ;;
    Darwin)
        source ${DOTFILES}/bash/bashrc_osx
	;;
    MINGW*)
        source ${DOTFILES}/bash/bashrc_windows
	pre-setup
	;;
esac

export PATH="$HOME/.local/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:$PATH"

if [ "$TERM" != "dumb" ] && [ -z "$(which dircolors)" ] && [ -f "${HOME}/.dir_colors" ]; then
    eval $(dircolors ~/.dir_colors)
fi

# git bash completion
source ${DOTFILES}/bash/git-completion.bash

# ... Bash customizations
alias pd='pushd'
#alias cdlast='cd $(lslast)'
#alias pyjson='python -mjson.tool'
alias grep='grep --color=auto'

export LESS='-R'

# Set key bindings to vi style
set -o vi

# Maven build
export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=256m"

# Default Editor
export EDITOR=vim

# git options
[ -d "${HOME}/.git-completion.bash" ] && source ~/.git-completion.bash

# powerline
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
# TODO Need more universal way to identify source location
# OSX location is different than XDG specs
source ~/anaconda/lib/python3.6/site-packages/powerline/bindings/bash/powerline.sh

function cpcd() { cp -i $1 $2 && cd $2; }
function mkdircd () { mkdir -p "$@" && eval cd "\"\$$#\""; }
function filter_ip() {
        grep -o "[0-9]\{1,3\}\(.[0-9]\{1,3\}\)\{3\}" < ${1:-/dev/stdin}
}

# Activate virtualenv in ./venv/bin/activate
function activate() {
        source ./venv/bin/activate
}

# Python dev related items
export PYTEST_ADDOPTS='--color=yes'

[ -f /usr/local/opt/dvm/dvm.sh ] && . /usr/local/opt/dvm/dvm.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[ -s "${HOME}/.bashrc_local" ] && source ${HOME}/.bashrc_local
